telegram:
  api-token: "xxxxxxxxxx:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
mqtt:
  domain: "192.168.1.x" # IP/NAME of the MQTT Server 
  port: 1883
  protocol: "MQTTv311" # Either "MQTTv31" or "MQTTv311"
  username: "mqtt_username"
  password: "mqtt_password"
  topic: "telebot"
  keepalive: 60
webserver:
  domain: "192.168.1.x" # IP of where the webserver is reachable by the Mediaplayer in HA
  port: 8000
other:
  loglevel: 3
  # 1: Error Only, 2: Warning, 3: Info, 4: Debug
allowed_contacts:
  # user id: Display Name
  # Only listed Contacts are allowed to send voice messages
  555555555: "trusted-contact-name"
